### ISSUE TITLE
Crashing on start

### ISSUE THREAD

**Issue by toas-koas** [scheibler/WalkersGuide-Android#2]
When I start the app it crash immediately

DivestOS, Android 13, Version 2.2.0

**Comment by scheibler** [comment]
Could you provide some more information please?

You've installed the app and it crashes immediately after you start it?
Could you uninstall and reinstall again please (just to be sure)?
Do you see the location permission request dialog before the crash occurs?

Are you familiar with adb (android debug bridge)?

**Comment by toas-koas** [comment]
Yeah it crash immediately after start. 
Reinstall doesn't solve the problem. 
I see the location permission dialog. 
I'm familiar with ADB
Here is a log

```
type: crash
osVersion: google/lineage_taimen/taimen:13/TQ2A.230505.002/eng.emy.20230504.220202:user/release-keys
package: org.walkersguide.android:23
process: org.walkersguide.android

java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=3, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {org.walkersguide.android/org.walkersguide.android.ui.activity.toolbar.tabs.MainActivity}: java.lang.IllegalArgumentException: provider "network" does not exist
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5335)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5374)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: java.lang.IllegalArgumentException: provider "network" does not exist
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3015)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.location.ILocationManager$Stub$Proxy.registerLocationListener(ILocationManager.java:1306)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1564)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1247)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1212)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1183)
	at org.walkersguide.android.sensor.PositionManager.startGPS(PositionManager.java:143)
	at org.walkersguide.android.ui.activity.ToolbarActivity.onRequestPermissionsResult(ToolbarActivity.java:432)
	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8810)
	at android.app.Activity.dispatchActivityResult(Activity.java:8668)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5328)
	... 13 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:59)
	at com.android.server.location.LocationManagerService.registerLocationListener(LocationManagerService.java:727)
	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:590)
	at android.os.Binder.execTransactInternal(Binder.java:1280)
	at android.os.Binder.execTransact(Binder.java:1244)


```

**Comment by scheibler** [comment]
Thank you for the crash log. That helps a lot.
Now I understand the problem. A fix should be easy to provide.

For testing purposes: Can you install a .apk file? If not, I also could provide a beta version on Google play.

**Comment by toas-koas** [comment]
Yes I can install an apk

**Comment by scheibler** [comment]
Then please try out:
https://www.walkersguide.org/downloads/WalkersGuide-2.2.1-b1-release.apk

**Comment by toas-koas** [comment]
It works. Thank you

**Comment by scheibler** [comment]
Version 2.3.0 released
